# Generated by Selenium IDE
import pytest
import time
import json
import random
from datetime import datetime
from time import sleep
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestRamonaConvocatorias():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def testRamonaConvocatorias(self):

    convocatoriasRamona = u""   #String ANSI para UTF8 se utiliza u
    
    self.driver.get("http://ramona.org.ar/convocatorias")
    self.driver.set_window_size(1050, 708)
    time.sleep(2)
    #es plural y debe ir elements
    #listConvocatorias = self.driver.find_elements(By.XPATH, "/html/body/div[1]/div[2]/div/div/div/div[1]/div[2]/div[1]")
    listConvocatorias = self.driver.find_elements_by_class_name("listview-item")
    print("Recolectando info, cant items: " + str(len(listConvocatorias)))
    for webElement in listConvocatorias:
      welinkAutor = webElement.find_element_by_tag_name("a") #xpath("./div/a")  #//tr/td[1]/a  la primer celda Tenia el link
      inscriptionLink = welinkAutor.get_attribute("href")
      tituloConvocatoria = welinkAutor.get_attribute("text")
      deadline = webElement.find_element_by_class_name("pretitle").text
      facilitador = webElement.find_element_by_class_name("postdescription").text
      #deadlineDate = datetime.strptime(deadline, '%d/%m/%Y')
      #today = datetime.now()



      convocatoriasRamona += "\t" + deadline + "\t" + tituloConvocatoria + "\t" + facilitador + "\t"+ inscriptionLink + "\n"
      print(facilitador)

    archivo = open("ConvocatoriasRamona.txt", "w", encoding="utf8")
    archivo.write(convocatoriasRamona)
    archivo.close()

    